# -*- coding: utf-8 -*-
"""Research and Summarization System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lkUuazgBavgtste_bDnI-k9BsFUTDBjw
"""

import os
import numpy as np
import faiss
from langgraph.graph import StateGraph, END
from typing import TypedDict, Annotated, List
import operator
import google.generativeai as genai
import json

# Configure Gemini model with environment variable
class ModelConfig:
    def __init__(self, model_name: str = "gemini-pro"):
        self.model_name = model_name
        self.api_key = os.getenv("GEMINI_API_KEY", "api")

    def initialize_model(self):
        genai.configure(api_key=self.api_key)
        return genai.GenerativeModel(self.model_name)

# Simulated knowledge store
class KnowledgeStore:
    def __init__(self):
        self.dimension = 256  # Changed dimension for embeddings
        self.index = faiss.IndexFlatL2(self.dimension)
        self.entries = []

    def add_entry(self, text: str):
        # Simulate embedding generation
        embedding = np.random.rand(self.dimension).astype('float32')
        self.index.add(np.array([embedding]))
        self.entries.append(text)

    def search(self, query: str, k: int = 2):
        # Simulate query embedding
        query_embedding = np.random.rand(self.dimension).astype('float32')
        distances, indices = self.index.search(np.array([query_embedding]), k)
        return [self.entries[i] for i in indices[0] if i < len(self.entries)]

# Initialize knowledge store with dummy data
ks = KnowledgeStore()
ks.add_entry("Python is a powerful language for scripting, automation, and machine learning.")
ks.add_entry("LangGraph enables complex workflows with stateful agents.")
ks.add_entry("AI involves creating systems that mimic human intelligence.")
ks.add_entry("Deep learning uses layered neural networks for advanced pattern recognition.")

# Mock web lookup function
def web_lookup(query: str) -> str:
    """Mock web lookup simulating real-time search."""
    mock_data = {
        "ai trends": "AI trends include generative models, ethical AI frameworks, and quantum computing integration.",
        "recent tech": "Recent tech news highlights advancements in AI chips and cloud computing solutions.",
        "current news": "Current news reports focus on AI-driven automation and data privacy regulations."
    }
    query_lower = query.lower()
    for key, response in mock_data.items():
        if any(keyword in query_lower for keyword in key.split()):
            return response
    return f"Mock lookup result for: {query}"

# State definition
class QueryState(TypedDict):
    input_query: str
    history: Annotated[List[dict], operator.add]
    path: str
    output: str

# Classifier Agent
def classifier_agent(state: QueryState) -> QueryState:
    query = state["input_query"]
    prompt = f"""
    Classify the query to determine processing path:
    - 'lookup' for queries with 'trends', 'recent', 'current', or 'news'
    - 'knowledge' for technical or programming-related queries
    - 'general' for other queries

    Query: {query}

    Return only one word: lookup, knowledge, or general
    """
    try:
        model = ModelConfig().initialize_model()
        response = model.generate_content(prompt)
        path = response.text.strip().lower()
        path = path if path in ['lookup', 'knowledge', 'general'] else 'general'
    except Exception as e:
        print(f"Classifier error: {e}")
        path = 'general'

    return {
        "history": state["history"] + [{"agent": "classifier", "content": f"Path: {path}"}],
        "path": path
    }

# Lookup Agent
def lookup_agent(state: QueryState) -> QueryState:
    query = state["input_query"]
    try:
        result = web_lookup(query)
    except Exception as e:
        result = f"Lookup failed: {str(e)}"

    return {
        "history": state["history"] + [{"agent": "lookup", "content": result}],
        "output": result
    }

# Knowledge Agent
def knowledge_agent(state: QueryState) -> QueryState:
    query = state["input_query"]
    try:
        results = ks.search(query, k=2)
        result = results[0] if results else "No relevant information found."
    except Exception as e:
        result = f"Knowledge search failed: {str(e)}"

    return {
        "history": state["history"] + [{"agent": "knowledge", "content": result}],
        "output": result
    }

# General Agent
def general_agent(state: QueryState) -> QueryState:
    query = state["input_query"]
    prompt = f"Provide a concise answer to: {query}"
    try:
        model = ModelConfig().initialize_model()
        response = model.generate_content(prompt)
        result = response.text.strip()
    except Exception as e:
        result = f"General response failed: {str(e)}"

    return {
        "history": state["history"] + [{"agent": "general", "content": result}],
        "output": result
    }

# Output Formatter Agent
def formatter_agent(state: QueryState) -> QueryState:
    prompt = f"""
    Format the response into a concise JSON object for the query: {state['input_query']}
    Response: {state['output']}

    Return a JSON string with 'query' and 'answer' fields.
    """
    try:
        model = ModelConfig().initialize_model()
        response = model.generate_content(prompt)
        result = json.loads(response.text.strip())
    except Exception as e:
        result = {"query": state["input_query"], "answer": state["output"]}

    return {
        "history": state["history"] + [{"agent": "formatter", "content": json.dumps(result)}],
        "output": json.dumps(result)
    }

# Build workflow
workflow = StateGraph(QueryState)
workflow.add_node("classifier", classifier_agent)
workflow.add_node("lookup", lookup_agent)
workflow.add_node("knowledge", knowledge_agent)
workflow.add_node("general", general_agent)
workflow.add_node("formatter", formatter_agent)

workflow.set_entry_point("classifier")
workflow.add_conditional_edges(
    "classifier",
    lambda state: state["path"],
    {
        "lookup": "lookup",
        "knowledge": "knowledge",
        "general": "general"
    }
)
workflow.add_edge("lookup", "formatter")
workflow.add_edge("knowledge", "formatter")
workflow.add_edge("general", "formatter")
workflow.add_edge("formatter", END)

graph = workflow.compile()

# Process query
def process_query(query: str) -> str:
    try:
        initial_state = {"input_query": query, "history": [], "path": "", "output": ""}
        result = graph.invoke(initial_state)
        return result["output"]
    except Exception as e:
        return json.dumps({"query": query, "answer": f"Error: {str(e)}"})

# Test queries
if __name__ == "__main__":
    test_queries = [
        "What are recent AI trends?",
        "Describe Python scripting",
        "What is the capital of Japan?"
    ]
    for query in test_queries:
        response = process_query(query)
        print(f"\nQuery: {query}")
        print(f"Response: {response}")
        print("-" * 40)