# -*- coding: utf-8 -*-
"""content_generation_system

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DGuBR7DHvWC51-7H49hf2yW2li1EmCXx
"""

```python
!pip install pyautogen google-generativeai --quiet

import os
import google.generativeai as genai
from autogen import AssistantAgent, UserProxyAgent

# Configure API and model
class ModelConfig:
    def __init__(self, model_name: str = "gemini-pro"):
        self.api_key = os.getenv("GEMINI_API_KEY", "your_gemini_api_key")
        if not self.api_key or self.api_key == "your_gemini_api_key":
            raise EnvironmentError("GEMINI_API_KEY not set")
        genai.configure(api_key=self.api_key)
        self.llm_config = {
            "config_list": [
                {
                    "model": model_name,
                    "api_type": "google",
                    "api_key": self.api_key
                }
            ],
            "temperature": 0.5,  # Changed from default 0.7
            "max_tokens": 800    # Added token limit
        }

# Agents
writer = AssistantAgent(
    name="Article_Writer",
    llm_config=ModelConfig().llm_config,
    system_message="""You are the Article Writer Agent.
    Create clear, engaging, and accurate content on Agentic AI.
    Focus on technical accuracy and readability for a general audience."""
)

reviewer = UserProxyAgent(
    name="Article_Reviewer",
    code_execution_config=False,
    human_input_mode="NEVER",
    llm_config=ModelConfig().llm_config,
    system_message="""You are the Article Reviewer Agent.
    Evaluate content for clarity, accuracy, and structure.
    Provide specific feedback and improvement suggestions."""
)

# Main function
def run_content_generator():
    print("=== Content Generation System ===")
    print("Generate and review an article on Agentic AI.")

    task = """
    Write a concise article about Agentic AI.
    Cover its definition, functionality, challenges, and potential benefits.
    Aim for 300-500 words, suitable for a general tech audience.
    """

    try:
        # Initiate chat
        print("\n🚀 Starting Content Creation...")
        result = reviewer.initiate_chat(
            recipient=writer,
            message=task,
            max_turns=4  # Added limit for efficiency
        )

        # Extract final article and feedback
        article = writer.last_message().get("content", "No article generated")
        feedback = reviewer.last_message().get("content", "No feedback provided")

        # Save output as Markdown
        output = f"""
# Agentic AI Article

## Final Article
{article}

## Reviewer Feedback
{feedback}
"""
        with open("agentic_ai_article.md", "w") as f:
            f.write(output)

        print("\n" + "="*40)
        print("✅ Article Generation Complete!")
        print("📝 Saved to agentic_ai_article.md")
        return output

    except Exception as e:
        print(f"System error: {e}")
        return None

# Fallback mode
def basic_article_generator():
    print("=== Basic Article Generator ===")
    config = ModelConfig()
    model = genai.GenerativeModel(model_name="gemini-pro")
    task = """
    Write a short article (200-300 words) about Agentic AI.
    Explain what it is, how it works, challenges, and opportunities.
    """
    try:
        response = model.generate_content(task)
        article = response.text
        output = f"""
# Agentic AI Article (Basic)

## Article
{article}

## Note
Generated without agent interaction due to fallback mode.
"""
        with open("basic_agentic_ai_article.md", "w") as f:
            f.write(output)

        print("\n📝 Basic article generated!")
        print("📄 Saved to basic_agentic_ai_article.md")
        return output
    except Exception as e:
        print(f"Fallback error: {e}")
        return None

if __name__ == "__main__":
    try:
        run_content_generator()
    except Exception as e:
        print(f"Multi-agent error: {e}")
        print("Switching to basic generator...")
        basic_article_generator()
```