# -*- coding: utf-8 -*-
"""portfolio_advisor_system

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DGuBR7DHvWC51-7H49hf2yW2li1EmCXx
"""

!pip install pyautogen google-generativeai pyyaml --quiet

import google.generativeai as genai
from autogen import AssistantAgent, UserProxyAgent, GroupChat, GroupChatManager
import os
import yaml
from typing import Dict

# Configure API and model
class Config:
    def __init__(self, model_name: str = "gemini-pro"):
        self.api_key = os.getenv("GEMINI_API_KEY", "your_gemini_api_key")
        if not self.api_key or self.api_key == "your_gemini_api_key":
            raise EnvironmentError("GEMINI_API_KEY not set")
        genai.configure(api_key=self.api_key)
        self.llm_config = {
            "config_list": [
                {
                    "model": model_name,
                    "api_key": self.api_key,
                    "api_type": "google"
                }
            ],
            "temperature": 0.6,  # Changed from 0.7
            "max_tokens": 1200   # Added token limit
        }

# Portfolio state logic
class PortfolioLogic:
    def __init__(self):
        self.strategy_type = None

    def evaluate_strategy(self, portfolio: Dict) -> str:
        """Evaluate portfolio to decide Aggressive vs Conservative strategy."""
        total_assets = portfolio['fixed_deposits'] + portfolio['mutual_funds'] + portfolio['property']
        income = portfolio['income']
        if total_assets < income * 1.5:  # Changed threshold from 2
            self.strategy_type = "AGGRESSIVE"
        else:
            self.strategy_type = "CONSERVATIVE"
        return self.strategy_type

# Agents
client_proxy = UserProxyAgent(
    name="Client_Proxy",
    human_input_mode="NEVER",
    system_message="""You are the Client Proxy.
    Initiate portfolio analysis by providing user financial data."""
)

asset_analyzer = AssistantAgent(
    name="Asset_Analyzer",
    llm_config=Config().llm_config,
    system_message="""You are the Asset Analysis Agent.
    Analyze the user's financial portfolio and recommend Aggressive or Conservative strategy.
    Provide:
    1. Asset summary
    2. Strategy recommendation
    3. Rationale for the recommendation"""
)

aggressive_investor = AssistantAgent(
    name="Aggressive_Investor",
    llm_config=Config().llm_config,
    system_message="""You are the Aggressive Investment Agent.
    Recommend high-return investments:
    - Equity funds
    - Tech stocks
    - Venture capital options
    Provide specific suggestions with potential returns."""
)

conservative_investor = AssistantAgent(
    name="Conservative_Investor",
    llm_config=Config().llm_config,
    system_message="""You are the Conservative Investment Agent.
    Recommend stable investments:
    - Bonds
    - Fixed income securities
    - Blue-chip stocks
    Provide suggestions focused on low risk."""
)

financial_planner = AssistantAgent(
    name="Financial_Planner",
    llm_config=Config().llm_config,
    system_message="""You are the Financial Planner.
    Compile a detailed financial plan using:
    - Asset analysis
    - Investment suggestions
    Provide a comprehensive report with actionable steps."""
)

# Main function
def run_financial_advisor():
    print("=== Financial Advisor System ===")
    print("Analyze your portfolio and get tailored investment advice.")

    try:
        # Collect user inputs
        income = float(input("Annual income: "))
        fixed_deposits = float(input("Fixed deposits amount: "))
        mutual_funds = float(input("Mutual funds amount: "))
        property = float(input("Property value: "))

        portfolio = {
            'income': income,
            'fixed_deposits': fixed_deposits,
            'mutual_funds': mutual_funds,
            'property': property
        }

        # Evaluate strategy
        logic = PortfolioLogic()
        strategy = logic.evaluate_strategy(portfolio)
        print(f"\n✅ Strategy Selected: {strategy} Investment Approach")

        # Select investment agent
        investment_agent = aggressive_investor if strategy == "AGGRESSIVE" else conservative_investor

        # Create group chat
        chat_group = GroupChat(
            agents=[client_proxy, asset_analyzer, investment_agent, financial_planner],
            messages=[],
            max_round=6  # Changed from 8
        )

        chat_coordinator = GroupChatManager(
            groupchat=chat_group,
            llm_config=Config().llm_config
        )

        # Start conversation
        initial_message = f"""
        Financial Planning Request:

        Portfolio Data:
        - Income: ₹{income:,.2f}
        - Fixed Deposits: ₹{fixed_deposits:,.2f}
        - Mutual Funds: ₹{mutual_funds:,.2f}
        - Property: ₹{property:,.2f}

        Strategy: {strategy}

        Asset_Analyzer: Analyze the portfolio and provide insights.
        {investment_agent.name}: Suggest {strategy.lower()} investments.
        Financial_Planner: Create a detailed financial plan.
        """

        print("\n🚀 Initiating Analysis...")
        result = client_proxy.initiate_chat(
            recipient=chat_coordinator,
            message=initial_message,
            max_turns=4  # Changed from 6
        )

        # Save output to YAML
        output = {
            "portfolio": portfolio,
            "strategy": strategy,
            "analysis": asset_analyzer.last_message().get("content", "No analysis"),
            "investments": investment_agent.last_message().get("content", "No suggestions"),
            "plan": financial_planner.last_message().get("content", "No plan")
        }
        with open("financial_plan.yaml", "w") as f:
            yaml.dump(output, f, allow_unicode=True)

        print("\n" + "="*40)
        print("✅ Financial Planning Complete!")
        print(f"📊 Strategy: {strategy}")
        print(f"💰 Total Assets: ₹{fixed_deposits + mutual_funds + property:,.2f}")
        print("📄 Plan saved to financial_plan.yaml")

        return output

    except Exception as e:
        print(f"System error: {e}")
        return None

# Simplified fallback
def basic_financial_report():
    print("=== Basic Financial Report ===")
    portfolio = {
        "income": 500000,
        "fixed_deposits": 200000,
        "mutual_funds": 150000,
        "property": 1000000
    }
    logic = PortfolioLogic()
    strategy = logic.evaluate_strategy(portfolio)

    output = {
        "portfolio": portfolio,
        "strategy": strategy,
        "recommendations": []
    }

    if strategy == "AGGRESSIVE":
        output["recommendations"] = ["Invest in tech ETFs (10-15% return)", "Explore startup equity"]
    else:
        output["recommendations"] = ["Increase bonds allocation", "Focus on dividend stocks"]

    output["insights"] = [f"Portfolio size: ₹{sum([portfolio['fixed_deposits'], portfolio['mutual_funds'], portfolio['property']]):,.2f}"]

    with open("basic_financial_report.yaml", "w") as f:
        yaml.dump(output, f, allow_unicode=True)

    print(f"\n📊 Strategy: {strategy}")
    print(f"💰 Total Assets: ₹{sum([portfolio['fixed_deposits'], portfolio['mutual_funds'], portfolio['property']]):,.2f}")
    print(f"📄 Saved to basic_financial_report.yaml")

if __name__ == "__main__":
    try:
        run_financial_advisor()
    except Exception as e:
        print(f"Multi-agent error: {e}")
        print("Switching to basic report...")
        basic_financial_report()